services:
  - type: web
    name: telegram-21-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py --webhook
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_HOST
        sync: false
      - key: IS_RENDER
        value: "true" 